name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install Frontend Dependencies (React)
      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install
          npm run build  # Build React frontend

      # Install Backend Dependencies (Node.js)
      - name: Install Backend Dependencies
        run: |
          cd server
          npm install
          npm test  # Run backend tests if available

      # Deployment Step 
      - name: Deployment Step 🚀
        run: echo "Simulating deployment... "
